# .github/workflows/release.yml
name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
      - ci
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            x86_64-pc-windows-gnu,
            x86_64-unknown-linux-musl,
            x86_64-apple-darwin,
          ]
    steps:
      - uses: actions/checkout@master
      - name: Rust Release binary
        uses: Douile/rust-build.action@v0.1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
